enableGlobalCache: false

nodeLinker: pnp

plugins:
  - checksum: 851142c703628545884caa3bd31d2135c224c16940418595a146831d54651c31988cf1226f3ebb4a343836d50287b511d08696cf1e60972ca704db8b40ad71c7
    path: .yarn/plugins/@yarnpkg/plugin-prevent-multiple-instances.cjs
    spec: "https://github.com/dobesv/berry/releases/download/plugin-prevent-multiple-instances-v1/plugin-prevent-multiple-instances.js"

pnpMode: loose

preventMultipleInstances:
- 'virtual:*'
